### ISSUE TITLE
[Feature Request] max-lines style option

### ISSUE THREAD

**Issue by fogine** [DaveDavenport/rofi#628]
## Version

`1.3.1 - 1.3.1-685-g4d728e3c (master)`

The `lines` option defines fixed number of lines. It would be cool to let rofi auto adjust its height depending on number of items received...

Example: 

```css
#window horibox listview box {
    layout:     vertical;
    spacing:    0px;
    lines:      5;
}
```
I propose for options `max-lines` & `min-lines`.
`max-lines` would automatically adjust height to number of received items if number of items is lower than `max-lines` value.

Thank you for your great contributions to OS!
