### ISSUE TITLE
Aligning listview elements to the right

### ISSUE THREAD

**Issue by pasimko** [DaveDavenport/rofi#842]
## Version
Version: 1.5.1-dirty (tags/1.5.1)

##Config
```
/* vim:ft=css */
* {
	background-color:			#2f343f;
	color:					#D1D5DC;
	border-color:				#D1D5DC;
	font:						"Hack Regular 12";
}
#window {
    /* background-color: @background;*/
    border:           1;
    padding:         5;
	width:			  20%;
    children:         [ horibox ];
}
#scrollbar {
	display: none;
}
#horibox {
	orientation: horizontal;           
	children:    [ prompt, entry, listview ];
}

#listview {
	width:			 10px;
	margin-right:	 0px;
	layout:    		 horizontal;
	lines:     		 1;
}
#element selected {
	color: #7191B1;
	horizontal-align: 0;
	margin-right: 0px;
}
```

![Result](https://user-images.githubusercontent.com/20600978/43370400-496f2c88-9333-11e8-8ca5-56495aa7d929.png)

Is there a way for me to align the suggestions to the right?

**Comment by DaveDavenport** [comment]
Not with listview in horizontal mode. (should see if this can be fixed) 
```css
/* vim:ft=css */                                   
* {                                                
    background-color:           #2f343f;           
    color:                  #D1D5DC;               
    border-color:               #D1D5DC;           
    font:                       "Hack Regular 12"; 
}                                                  
#window {                                          
    /* background-color: @background;*/            
    border:           1;                           
    padding:         5;                            
    children:         [ horibox ];                 
}                                                  
#scrollbar {                                       
    display: none;                                 
}                                                  
#horibox {                                         
    orientation: horizontal;                       
    children:    [ prompt, entry, listview ];      
}                                                  
#entry {                                           
    expand: false;                                 
width: 20em;                                       
}                                                  
#listview {                                        
    expand: true;                                  
    width:           130em;                        
    margin-right:    0px;                          
lines: 1;                                          
}                                                  
#element {                                         
    horizontal-align: 1;                           
}                                                  
#element selected {                                
    color: #7191B1;                                
    margin-right: 0px;                             
}                                                  
                                                   
```
Aligns it to the right.
